all:
  children:
    masters:
      hosts:
        vm-master:
          ansible_host: 10.91.214.10

    workers:
      hosts:
        vm-worker-1:
          ansible_host: 10.91.214.11
        vm-worker-2:
          ansible_host: 10.91.214.12

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3