apiVersion: v1
kind: Namespace

metadata:
  name: nginxapp2

---
apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: nginx
  namespace: argocd

spec:
  project: default
  source:
    repoURL: 'https://github.com/antonioflaviosf/eng_lab.git'
    targetRevision: main
    path: platform/kubernetes/apps/nginx
  
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginxapp2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx2-ingress
  namespace: nginxapp
  # A annotation foi removida daqui
spec:
  ingressClassName: traefik  # Nova forma padrão de definir o controller
  rules:
  - host: nginx2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80