- name: Run master setup
  include_tasks: master.yml
  when: "'masters' in group_names"

# 🔥 Espera a API subir antes de qualquer coisa
- name: Wait for k3s API to be ready
  wait_for:
    port: 6443
    host: "{{ inventory_hostname }}"
    delay: 5
    timeout: 120
  when: "'masters' in group_names"

- name: Get node token from master
  command: cat /var/lib/rancher/k3s/server/node-token
  register: node_token_raw
  when: "'masters' in group_names"

- name: Set token fact on master
  set_fact:
    node_token: "{{ node_token_raw.stdout }}"
  when: "'masters' in group_names"

# 🔥 garante que todos esperem o master terminar
- name: Wait for master token to be available
  wait_for:
    timeout: 30
  delegate_to: localhost

- name: Set token for all hosts
  set_fact:
    node_token: "{{ hostvars[groups['masters'][0]].node_token }}"

- name: Run worker setup
  include_tasks: worker.yml
  when: "'workers' in group_names"

#  --- BACKUP
# - name: Run master setup
#   include_tasks: master.yml
#   when: "'masters' in group_names"

# - name: Get node token from master
#   command: cat /var/lib/rancher/k3s/server/node-token
#   register: node_token_raw
#   when: "'masters' in group_names"

# - name: Set token fact
#   set_fact:
#     node_token: "{{ node_token_raw.stdout }}"
#   when: "'masters' in group_names"

# - name: Share token with all hosts
#   set_fact:
#     node_token: "{{ hostvars[groups['masters'][0]]['node_token'] }}"
  
# - name: Run worker setup
#   include_tasks: worker.yml
#   when: "'workers' in group_names"